name: Deploy to Firebase Hosting on push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: FirebaseExtended/actions/firebase-hosting-deploy@v0
        with:
          project: <ID_DEL_PROYECTO>
          token: ${{ secrets.FIREBASE_TOKEN }}
